////////////////////////////////////////////////////////////
// Syntax tests
//
// Author: Sergi Reyner
//
// (also figure out how to alter/tweak/replace the syntax)
////////////////////////////////////////////////////////////
EVAL File fileIn: 'gossip/JavaWrapper.st'
EVAL File fileIn: 'gossip/Reactor.st'
EVAL File fileIn: 'gossip/Door.st'
EVAL File fileIn: 'gossip/Room.st'
EVAL File fileIn: 'gossip/GameRegistry.st'
EVAL File fileIn: 'gossip/SetupRooms.st'
EVAL SetupRooms setup
EVAL Workspace open
//EVAL Transcript open
